_wandb:
    value:
        cli_version: 0.21.1
        e:
            hzblitp9y9shfgz73fr5smapzqx659sb:
                codePath: finetune/train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "107374182400"
                        used: "31149228032"
                email: raghib@blockstak.ai
                executable: /usr/bin/python
                git:
                    commit: 835ac7cd1870fa1fa5e342e14260c2d68cabb2e7
                    remote: https://github.com/canopyai/Orpheus-TTS.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-36d163b7-8c60-3ca9-f46a-1f56a919e8f1
                host: fd9247a03eed
                memory:
                    total: "1081999663104"
                os: Linux-6.8.0-49-generic-x86_64-with-glibc2.35
                program: /root/Orpheus-TTS/finetune/train.py
                python: CPython 3.11.13
                root: /root/Orpheus-TTS/finetune
                startedAt: "2025-08-13T20:04:34.189387Z"
                writerId: hzblitp9y9shfgz73fr5smapzqx659sb
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 71
            "3":
                - 13
            "4": 3.11.13
            "5": 0.21.1
            "6": 4.55.1
            "12": 0.21.1
            "13": linux-x86_64
