# CHANGE THIS TO YOUR OWN DATASET
# ==============================
# Dataset and Model Config
# ==============================
TTS_dataset: "<your-hf-username>/<your-dataset-name>"   # Hugging Face dataset repo ID
model_name: "<your-hf-username>/<your-model-name>"      # Pretrained model repo ID

# ==============================
# Training Arguments
# ==============================
epochs: <num_epochs>            # e.g., 3
batch_size: <batch_size>        # e.g., 8
number_processes: <num_processes> # Number of parallel processes (e.g., 4)
pad_token: <pad_token_id>       # Token ID used for padding (integer)
save_steps: <save_every_n_steps> # How often to save model checkpoints
eval_steps: <eval_every_n_steps> # How often to evaluate the model
learning_rate: <learning_rate>  # e.g., 5.0e-5
upload_repo_id: "<your-hf-username>/<your-output-model-repo>"  # Where to push trained model

# ==============================
# Naming and Paths
# ==============================
save_folder: "<path-to-save-checkpoints>"  # Local path to store outputs
project_name: "<project-name>"             # For experiment tracking/logging
run_name: "<run-name>"                     # Specific identifier for this run